apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleci-deployment
spec:
  selector:
    matchLabels:
      app: cci-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: cci-demo
    spec:
      containers:
      - name: cci-demo
        image: skywalke34/cci-demo-docker:latest
        ports:
        - containerPort: 80

---
#HTTPS://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: cci-demo-service
spec:
  selector:
    app: cci-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort
